### ISSUE TITLE
Long passwords

### ISSUE THREAD

**Issue by roq** [floyd-fuh/JKS-private-key-cracker-hashcat#1]
I created a keystore with a length 20 password, then used your conversion utility. I then added the password to a dictionary file, then ran hashcat in mode 0 (straight dictionary), -m 15500, with the known password in the file. It did not crack the password (exhausted). It seems like hashcat is truncating the passwords in the dictionary. What am I doing wrong? Thanks.

**Comment by floyd-fuh** [comment]
Hi, thanks for the issue report. I pinged the hashcat guys because if I remember correctly there was some work done regarding "maximum length of password" in hashcat, so this might not be a bug of this preparation script.

In the meantime, could you try to crack the password with the jksprivk_crack.py script included in this repository? You will need to modify the script to use your password rather than try numeric password. You can do that by changing the second line of:

```
def next_brute_force_token(alphabet, minimum=1, maximum=10):
#return ["\x001\x002\x003\x004\x005\x006"]
```

You have to remove the # comment and include null bytes before each character of your password. So if your password is "HELLO", it would be:

```
def next_brute_force_token(alphabet, minimum=1, maximum=10):
    return ["\x00H\x00E\x00L\x00L\x00O"]
```

Then run the script with the output of JksPrivkPrepare.jar as an argument

**Comment by floyd-fuh** [comment]
Also see https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#what_is_the_maximum_supported_password_length_for_optimized_kernels

**Comment by floyd-fuh** [comment]
I just got this from the hashcat maintainers: "just make sure to not use -O with latest version, then it support passwords up to length 256". Can you please check if that works for you? If not, can you please provide your hashcat version?

**Comment by roq** [comment]
Hooray! Thank you so much. I checked the version and it was 3.6.0. I upgraded to 4.0.1 and it cracked the password as expected.

**Comment by floyd-fuh** [comment]
I changed the README to make sure people know they better use hashcat 4. Happy cracking!
